# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-13 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('girlnum', models.IntegerField()),
                ('boynum', models.IntegerField()),
                ('isdelete', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TestStudents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.BooleanField(default=True)),
                ('age', models.IntegerField()),
                ('scont', models.CharField(max_length=20)),
                ('isdelete', models.BooleanField()),
                ('tgrade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApp.TestGrade')),
            ],
        ),
    ]
