# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-18 21:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0002_auto_20180715_0441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teststudent',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='teststudent',
            name='createTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teststudent',
            name='lastTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='teststudent',
            table='student',
        ),
    ]
